---
apiVersion: v1
kind: Service
metadata:
  namespace: itsmetommy
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
  - port: 8080
    name: jenkins-ui
  - port: 50000
    name: jnlp
  selector:
    app: jenkins-master
